server:
    port: 0
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:         
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411