server:
  port: 8888

spring:
  application: 
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ciberado/sc-configuracion #aquí tenemos la config
          basedir: target/config #aquí queremos hacer el clone

